### ISSUE TITLE
Error: name 'CutterBindings' is not defined

### ISSUE THREAD

**Issue by Emi1305** [radareorg/cutter#2287]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 1.10.3
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded from release
  - [ ] Distribution repository
* File format: Plugin

**

I'm working on a python plugin. A part of my code looks like this:

```
import cutter
import CutterBindings
class MyWrapper:
    def __init__(self):
        self._core = CutterBindings.CutterCore.instance()
        logger.info('self._core: {}'.format(type(self._core)))
        self._config = CutterBindings.Configuration.instance()
        logger.info('self._config: {}'.format(type(self._config)))

# In another python file, here disassembler is an instance of my wrapper
for node_address in nodes_addresses:
            logger.debug('Logging CutterBindings {} {} {} {}'
                   .format(disassembler,
                           disassembler[self.lctx],
                           disassembler[self.lctx]._core,
                           disassembler[self.lctx]._core.getBBHighlighter()))
            disassembler[self.lctx]._core.getBBHighlighter().highlight(self.director.coverage.nodes.get(node_address, None), color)

```

When getting the core and configuration instance it works fine, but when I try to highlight something I get the following error:

```
INFO: self._core: <class 'CutterBindings.CutterCore'>
INFO: self._config: <class 'CutterBindings.Configuration'>
DEBUG: Exported Cutter core
................
DEBUG: Logging CutterBindings <lighthouse.util.disassembler.cutter_api.CutterCoreAPI object at 0x7fe7552c3400> <lighthouse.util.disassembler.cutter_api.CutterContextAPI object at 0x7fe7550d4d90> <CutterBindings.CutterCore(0x5643b4226ae0) at 0x7fe755259500> <CutterBindings.BasicBlockHighlighter object at 0x7fe74c743dc0>
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/signature/loader.py", line 105, in seterror_argument
ERROR: return errorhandler.seterror_argument(args, func_name)
ERROR:   File "/usr/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/signature/errorhandler.py", line 101, in seterror_argument
ERROR: func = eval(func_name, namespace)
ERROR:   File "<string>", line 1, in <module>
ERROR: NameError
ERROR: :
ERROR: name 'CutterBindings' is not defined
```
**

The error is that CutterBindings is available in some contexts but is not available in others.

**To Reproduce**

1. Clone https://github.com/Emi1305/lighthouse
2. Checkout `cutter_integration` branch
3. Symlink contents of the `plugin` directory to the cutter plugin directory (i.e. `$HOME/.local/share/RadareOrg/Cutter/plugins/python`)
4. Open the testcase file `boombox.exe`
5. Go to `File`>`Lighthouse - Load coverage file...`
6. Load any of the coverage files in the same testcase directory
7. Observe it crashes
8. Log is available at `$HOME/.local/share/RadareOrg/Cutter/lighthouse_logs/lighthouse.<pid>.log`
9. Observe at the end of the log that the logger was able to successfully log the `CutterBindings` settings but crashes right after when attempting to use it

**Expected behavior**

`CutterBindings` being available in every context and working

**Comment by karliss** [comment]
Why do you think that `CutterBindings` is a thing? The sample python plugin is using `cutter.CutterPlugin` instead of `CutterBindings.CutterPlugin`.

**Comment by karliss** [comment]
Ok, binding generator use CutterBindings. Seems like a bit of inconsistency Will have to take a look at what actually gets generated and try it to tell you more.
