### ISSUE TITLE
v1.1 segfault when loading a saved project.

### ISSUE THREAD

**Issue by mereckaj** [radareorg/cutter#260]
Cutter 1.1 seems to segfault when loading saved projects, about 1 in 10 loads will do so. Only tried for projects that analyze PE executables on Linux.

Here the backtrace from the coredump. 

Coredump if this will help debug the issue is [here](https://drive.google.com/file/d/13_hv93t28jOH6-ZB8LzMzNX5FGolWnc6/view?usp=sharing)

 
```
#0  0x00007f7769db84d0 in QGraphicsItem::scene() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007f7769ded199 in QGraphicsScene::removeItem(QGraphicsItem*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x000055aaae50f9d6 in VisualNavbar::drawCursor (this=0x55aaaef30a40) at ../src/widgets/VisualNavbar.cpp:329
#3  0x000055aaae50fba6 in VisualNavbar::on_seekChanged (this=0x55aaaef30a40, addr=4198400) at ../src/widgets/VisualNavbar.cpp:348
#4  0x000055aaae5328cd in VisualNavbar::qt_static_metacall (_o=0x55aaaef30a40, _c=QMetaObject::InvokeMetaMethod, _id=7, _a=0x7ffc476f9280) at moc_VisualNavbar.cpp:107
#5  0x00007f7768dfbd55 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x000055aaae52a8b7 in CutterCore::seekChanged (this=0x55aaae80c180 <(anonymous namespace)::Q_QGS_uniqueInstance::innerFunction()::holder>, _t1=4198400) at moc_cutter.cpp:345
#7  0x000055aaae4310fd in CutterCore::cmd (this=0x55aaae80c180 <(anonymous namespace)::Q_QGS_uniqueInstance::innerFunction()::holder>, str=...) at ../src/cutter.cpp:158
#8  0x000055aaae432353 in CutterCore::seek (this=0x55aaae80c180 <(anonymous namespace)::Q_QGS_uniqueInstance::innerFunction()::holder>, addr=...) at ../src/cutter.cpp:350
#9  0x000055aaae432408 in CutterCore::seek (this=0x55aaae80c180 <(anonymous namespace)::Q_QGS_uniqueInstance::innerFunction()::holder>, offset=4198400) at ../src/cutter.cpp:356
#10 0x000055aaae44afbf in DisassemblerGraphView::seek (this=0x55aaaf5e32f0, addr=4198400, update_viewport=true) at ../src/widgets/DisassemblerGraphView.cpp:603
#11 0x000055aaae44b3b6 in DisassemblerGraphView::blockTransitionedTo (this=0x55aaaf5e32f0, to=0x55aaaf5c1c50) at ../src/widgets/DisassemblerGraphView.cpp:681
#12 0x000055aaae51721f in GraphView::showBlock (this=0x55aaaf5e32f0, block=0x55aaaf5c1c50, animated=false) at ../src/widgets/GraphView.cpp:830
#13 0x000055aaae516d8a in GraphView::showBlock (this=0x55aaaf5e32f0, block=..., animated=false) at ../src/widgets/GraphView.cpp:793
#14 0x000055aaae4487fc in DisassemblerGraphView::loadCurrentGraph (this=0x55aaaf5e32f0) at ../src/widgets/DisassemblerGraphView.cpp:200
#15 0x000055aaae4476de in DisassemblerGraphView::refreshView (this=0x55aaaf5e32f0) at ../src/widgets/DisassemblerGraphView.cpp:98
#16 0x000055aaae44a690 in DisassemblerGraphView::colorsUpdatedSlot (this=0x55aaaf5e32f0) at ../src/widgets/DisassemblerGraphView.cpp:457
#17 0x000055aaae4473d9 in DisassemblerGraphView::DisassemblerGraphView (this=0x55aaaf5e32f0, parent=0x55aaaf5cb200) at ../src/widgets/DisassemblerGraphView.cpp:84
#18 0x000055aaae4775af in MainWindow::initUI (this=0x55aaaf1dbff0) at ../src/MainWindow.cpp:204
#19 0x000055aaae4793dc in MainWindow::openProject (this=0x55aaaf1dbff0, project_name=...) at ../src/MainWindow.cpp:320
#20 0x000055aaae49c85e in NewFileDialog::loadProject (this=0x55aaaec7ad40, project=...) at ../src/dialogs/NewFileDialog.cpp:339
#21 0x000055aaae49b3a1 in NewFileDialog::on_projectsListWidget_itemDoubleClicked (this=0x55aaaec7ad40, item=0x55aaaeffa850) at ../src/dialogs/NewFileDialog.cpp:171
#22 0x000055aaae52cb19 in NewFileDialog::qt_static_metacall (_o=0x55aaaec7ad40, _c=QMetaObject::InvokeMetaMethod, _id=9, _a=0x7ffc476fa670) at moc_NewFileDialog.cpp:126
#23 0x000055aaae52cc2e in NewFileDialog::qt_metacall (this=0x55aaaec7ad40, _c=QMetaObject::InvokeMetaMethod, _id=9, _a=0x7ffc476fa670) at moc_NewFileDialog.cpp:160
#24 0x00007f7768dfbe19 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f7769d74bc2 in QListWidget::itemDoubleClicked(QListWidgetItem*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f7768dfbd55 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007f7769d2ec45 in QAbstractItemView::doubleClicked(QModelIndex const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007f7769d3aefa in QAbstractItemView::mouseDoubleClickEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007f7769b274af in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f7769bc79de in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007f7769d3ab8b in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f7768dccf3c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007f7769ae8575 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007f7769af03bf in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007f7768dcd258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007f7769aef392 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f7769b4188b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007f7769b43efa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007f7769ae859c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007f7769aefe64 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007f7768dcd258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007f776932d320 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#43 0x00007f776932ec65 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#44 0x00007f7769306cab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#45 0x00007f77624bed50 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#46 0x00007f7765ffdf67 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007f7765ffe1a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007f7765ffe22c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007f7768e260ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007f7768dcb2aa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007f7768dd4214 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x000055aaae42eebb in main (argc=1, argv=0x7ffc476fb928) at ../src/main.cpp:116
```

**Comment by gingerbeardman** [comment]
also getting this in 1.0

**Comment by gingerbeardman** [comment]
workaround is to save as zip: 

![screen shot 2018-01-24 at 11 22 06](https://user-images.githubusercontent.com/49612/35329759-e289092a-00f8-11e8-9192-0fb503dc250c.png)

**Comment by xarkes** [comment]
Is this bug still here?

**Comment by gingerbeardman** [comment]
I'll retest

**Comment by gingerbeardman** [comment]
I couldn't reproduce this.

**Comment by xarkes** [comment]
Me neither, that's why I closed :p
