### ISSUE TITLE
Themes with background-colors crash on Mac OS X

### ISSUE THREAD

**Issue by nezza** [radareorg/cutter#350]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac OS 10.12.6 
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)         | 17f7c0b5932eddc851721bd472f1d99d787c1ebf
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/nezza/156f78f902a4ac80195a4ce3b936a0be
| Theme | behelit

### Expected behavior

Not crashing

### Actual behavior

Application segfaults (always in different parts)

### Steps to reproduce the behavior 

This bug only happens with themes that have lines with fore and background colors, like behelit:
```
ec jmp rgb:000000 rgb:5f5fff
```
instead of
```
ec jmp rgb:5f5fff
```

The binary is not shareable but it happens with all kinds of binaries.
I can reproduce this bug well by scrolling through the disassembly view using the arrow keys and switching between Cutter and another application.

### Additional Logs, screenshots, source-code,  configuration dump, ...
Backtraces:
https://gist.github.com/nezza/6ce30a299c66d099d3c137381ce22dd4
https://gist.github.com/nezza/3792fc28528828f89b937189e9224d58

**Comment by thestr4ng3r** [comment]
I could track down the issue with asan. This happens on `e scr.color=3` after `eco behelit`, even in plain r2:
```
=================================================================
==52011==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300079f560 at pc 0x000119191822 bp 0x7fff50b31340 sp 0x7fff50b30ae0
WRITE of size 1 at 0x60300079f560 thread T0
    #0 0x119191821 in wrap_memmove (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1b821)
    #1 0x7fffb2bee437 in __sfvwrite (libsystem_c.dylib:x86_64+0x40437)
    #2 0x7fffb2bf8952 in __vfprintf (libsystem_c.dylib:x86_64+0x4a952)
    #3 0x7fffb2c1e422 in __v2printf (libsystem_c.dylib:x86_64+0x70422)
    #4 0x7fffb2c02b4f in vsprintf_l (libsystem_c.dylib:x86_64+0x54b4f)
    #5 0x7fffb2c3440b in __sprintf_chk (libsystem_c.dylib:x86_64+0x8640b)
    #6 0x111193d9b in r_cons_rgb_gen rgb.c:175
    #7 0x111193c1e in r_cons_rgb_str rgb.c:205
    #8 0x11119692c in r_cons_pal_update_event pal.c:520
    #9 0x10fa7992e in cb_color cconfig.c:1016
    #10 0x10fba5ed5 in r_config_set_i config.c:571
    #11 0x10f0dff3a in CutterCore::setConfig(QString const&, int) Cutter.cpp:488
    #12 0x10f409703 in TempConfig::set(QString const&, int) TempConfig.cpp:47
    #13 0x10f131714 in DisassemblerGraphView::loadCurrentGraph() DisassemblerGraphView.cpp:124
    #14 0x10f130ae1 in DisassemblerGraphView::refreshView() DisassemblerGraphView.cpp:116
    #15 0x10f1300c4 in DisassemblerGraphView::colorsUpdatedSlot() DisassemblerGraphView.cpp:495
    #16 0x10f12dffa in DisassemblerGraphView::DisassemblerGraphView(QWidget*) DisassemblerGraphView.cpp:102
    #17 0x10f1303ec in DisassemblerGraphView::DisassemblerGraphView(QWidget*) DisassemblerGraphView.cpp:24
    #18 0x10f1fc317 in MainWindow::initUI() MainWindow.cpp:186
    #19 0x10f1b10d7 in OptionsDialog::setupAndStartAnalysis(int, QList<QString>) OptionsDialog.cpp:159
    #20 0x10f22052a in MainWindow::displayAnalysisOptionsDialog(int, QList<QString>) MainWindow.cpp:316
    #21 0x10f21fd96 in MainWindow::openNewFile(QString const&, int, QList<QString>) MainWindow.cpp:289
    #22 0x10f4c7d07 in CutterApplication::CutterApplication(int&, char**) CutterApplication.cpp:81
    #23 0x10f4c8274 in CutterApplication::CutterApplication(int&, char**) CutterApplication.cpp:12
    #24 0x10f0d386b in main Main.cpp:30
    #25 0x7fffb2b79234 in start (libdyld.dylib:x86_64+0x5234)

0x60300079f560 is located 0 bytes to the right of 32-byte region [0x60300079f540,0x60300079f560)
allocated by thread T0 here:
    #0 0x1191ccb23 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x56b23)
    #1 0x111193b11 in r_cons_rgb_str rgb.c:193
    #2 0x11119692c in r_cons_pal_update_event pal.c:520
    #3 0x10fa7992e in cb_color cconfig.c:1016
    #4 0x10fba5ed5 in r_config_set_i config.c:571
    #5 0x10f0dff3a in CutterCore::setConfig(QString const&, int) Cutter.cpp:488
    #6 0x10f409703 in TempConfig::set(QString const&, int) TempConfig.cpp:47
    #7 0x10f131714 in DisassemblerGraphView::loadCurrentGraph() DisassemblerGraphView.cpp:124
    #8 0x10f130ae1 in DisassemblerGraphView::refreshView() DisassemblerGraphView.cpp:116
    #9 0x10f1300c4 in DisassemblerGraphView::colorsUpdatedSlot() DisassemblerGraphView.cpp:495
    #10 0x10f12dffa in DisassemblerGraphView::DisassemblerGraphView(QWidget*) DisassemblerGraphView.cpp:102
    #11 0x10f1303ec in DisassemblerGraphView::DisassemblerGraphView(QWidget*) DisassemblerGraphView.cpp:24
    #12 0x10f1fc317 in MainWindow::initUI() MainWindow.cpp:186
    #13 0x10f1b10d7 in OptionsDialog::setupAndStartAnalysis(int, QList<QString>) OptionsDialog.cpp:159
    #14 0x10f22052a in MainWindow::displayAnalysisOptionsDialog(int, QList<QString>) MainWindow.cpp:316
    #15 0x10f21fd96 in MainWindow::openNewFile(QString const&, int, QList<QString>) MainWindow.cpp:289
    #16 0x10f4c7d07 in CutterApplication::CutterApplication(int&, char**) CutterApplication.cpp:81
    #17 0x10f4c8274 in CutterApplication::CutterApplication(int&, char**) CutterApplication.cpp:12
    #18 0x10f0d386b in main Main.cpp:30
    #19 0x7fffb2b79234 in start (libdyld.dylib:x86_64+0x5234)
```
I am pretty sure this has been fixed by exactly this: https://github.com/radare/radare2/commit/7b5ab319f8f8917b33da21773d22ea83e574dd0a#diff-9c034f9ac7df95fdf0052687f15c796eR193
After this commit, everything works fine for me.

Since your r2 is on 70bd99da2 which is before the fix, it would explain it. The submodule is also still older than the fix. Could you please try again with current r2?

**Comment by xarkes** [comment]
ping @nezza

**Comment by xarkes** [comment]
Feel free to reopen if that's not fixed.
