### ISSUE TITLE
missing pip packages: jupyter_client and notebook 

### ISSUE THREAD

**Issue by 0x00rick** [radareorg/cutter#526]
### machine

    OS: Ubuntu 18.04 LTS x86_64 
    Kernel: 4.15.0-22-generic
    DE: Xfce

### cutter 

    Cutter v1.4 
    Using r2-2.5.0-160-gd774f579a

### noticed error

Upon start I could observe the following 2 stack traces:

```
Traceback (most recent call last):
  File "cutter_jupyter.py", line 5, in <module>
ModuleNotFoundError: No module named 'notebook'
Could not import cutter_jupyter.
```
and

```
Traceback (most recent call last):
  File "cutter_jupyter.py", line 4, in <module>
ModuleNotFoundError: No module named 'jupyter_client'
Could not import cutter_jupyter.
```

### Fix

The fix is simple as I just had to do `pip3 install notebook jupyter_client` to get rid of the error.
I'm unsure of that's just an issue on my end or a general issue.

**Comment by xarkes** [comment]
If you compiled it yourself, then it's an issue on your end.
You can disable this by removing `CUTTER_ENABLE_JUPYTER` definition when compiling.

**Comment by 0x00rick** [comment]
I see that would explain it then.
I followed the instructions for building in the readme

### Building

First you must clone the repository:

    git clone --recurse-submodules https://github.com/radareorg/cutter
    cd cutter
    ./build.sh

I guess most people would do exactly that when reading through the readme.
So imo including jupyter and notebook in the default install routine or an explicit notice to enable those in the readme would solve the confusion on if anything went wrong during install.

**Comment by 0x00rick** [comment]
will do a PR soon. 
You can review it later
