### ISSUE TITLE
Cutter crashes when initialising the radare python module

### ISSUE THREAD

**Issue by bodgergely** [radareorg/cutter#664]
I extracted the Appimage and when running the Cutter binary and opening its core file I get the below:

Ubuntu 64 bit 4.13.0-46-generic

```
#0 0x00007ff982622d3b in Py_InitModule4_64 () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#1 0x00007ff982a4a693 in init_radare_module () at python.c:264
#2 init (lang=) at python.c:376
#3 0x00007ff99c9224c8 in r_lang_add (lang=0x17e2730, foo=0x7ff982c4e2a0 <r_lang_plugin_python2>) at lang.c:132
#4 0x00007ff9a2bf0212 in __lib_lang_cb (pl=0x18f37f0, user=0x7ff9881fc010, data=0x7ff982c4e2a0 <r_lang_plugin_python2>) at libs.c:37
#5 0x00007ff99eedac6f in r_lib_run_handler (lib=0x18e3fd0, plugin=0x18f37f0, symbol=0x7ff982c4e880 <radare_plugin>) at lib.c:171
#6 0x00007ff99eedb394 in r_lib_open_ptr (lib=0x18e3fd0, file=0x7ffdce7c0c30 "/home/geri/.local/share/radare2/plugins/lang_python2.so", handler=0x19073b0,
stru=0x7ff982c4e880 <radare_plugin>) at lib.c:320
#7 0x00007ff99eedb1b1 in r_lib_open (lib=0x18e3fd0, file=0x7ffdce7c0c30 "/home/geri/.local/share/radare2/plugins/lang_python2.so") at lib.c:280
#8 0x00007ff99eedb570 in r_lib_opendir (lib=0x18e3fd0, path=0x18ce9b0 "/home/geri/.local/share/radare2/plugins") at lib.c:400
#9 0x00007ff9a2bf084b in r_core_loadlibs (core=0x7ff9881fc010, where=-1, path=0x0) at libs.c:91
#10 0x0000000000483f12 in CutterCore::CutterCore(QObject*) ()
#11 0x00000000004840be in CutterCore::getInstance() ()
#12 0x000000000054c342 in CutterApplication::CutterApplication(int&, char**) ()
#13 0x000000000047a4fc in main ()
(gdb)




0x7ff982622d26 <Py_InitModule4_64+22>   sub    rsp,0x218                                                                                                                 
0x7ff982622d2d <Py_InitModule4_64+29>   mov    QWORD PTR [rsp+0x8],rdx                                                                                                    
0x7ff982622d32 <Py_InitModule4_64+34>   call   0x7ff98261e930 <PyThreadState_Get>                                                                                         
0x7ff982622d37 <Py_InitModule4_64+39>   mov    rax,QWORD PTR [rax+0x8]
0x7ff982622d3b <Py_InitModule4_64+43> cmp QWORD PTR [rax+0x10],0x0     // Faulting instruction

(gdb) p $rax
$1 = 0
```

**Comment by bodgergely** [comment]
I was debugging this issue.
I am bit confused as the radare instance built by Cutter builds a python2 plugin.
On the other hand Cutter is linked with python3.
At the time when the plugin is being loaded it is the python2 language plugin that comes from the radare plugins directory. I also seem to have python2/python3 versions of the same functions being imported and used. 

Also when I manually change memory referencing offsets in PyModule_AddObject, Py_InitModule, PyModule_GetModuleDict etc offsets in gdb the program goes further and further depending on how many of these offsets I 'patch up'.

It all seems to be some issue with python2 getting mixed up with python3 libraries or vice versa.


```
(gdb) p foo
$31 = (RLangPlugin *) 0x7fffc0ef52a0 <r_lang_plugin_python2>
```
```
geri@geri-XPS-13-9360:~/workspace/hacking/radare2/cutter$ ldd ./build/Cutter | grep python
libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007f31ccea5000)

geri@geri-XPS-13-9360:~/workspace/hacking/radare2/cutter$ find /home/geri/.local/share/radare2/ -name "lang_py*"
/home/geri/.local/share/radare2/r2pm/git/radare2-bindings/libr/lang/p/lang_python2.so
/home/geri/.local/share/radare2/plugins/lang_python2.so
```

```
5.1                         y     0x00007fffc093cab0 <PyImport_GetModuleDict>
5.2                         y     0x00007ffff3847300 <PyImport_GetModuleDict>
7       breakpoint     keep y   <MULTIPLE>
7.1                         y     0x00007fffc08c8450 <PyModule_AddObject>
---Type <return> to continue, or q <return> to quit---
7.2                         y     0x00007ffff38526b0 <PyModule_AddObject>
```

**Comment by bodgergely** [comment]
Okay, I deleted the cached radare build I had under $HOME/.local/share/radare2 and did ./build.sh and now this whole python problem went away.
