### ISSUE TITLE
Cutter crashes after loading a dex file

### ISSUE THREAD

**Issue by ytrewqytrewqytrewqytrewq1** [radareorg/cutter#803]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  Ubuntu 17 64bit
| File format of the file you reverse (mandatory)      | dex
| Architecture/bits of the file (mandatory)            | N/A
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2 2.9.0-310-gcb62c376b
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://pastebin.com/vJXyxM2G

### Expected behavior
Cutter should open  and decompile the dex file
### Actual behavior
log:
```
Setting r2 prefix = "/tmp/.mount_CutterwjvmJV/usr"  for AppImage.
Setting PYTHONHOME = "/tmp/.mount_CutterwjvmJV/usr"  for AppImage.
PYTHONHOME = "/tmp/.mount_CutterwjvmJV/usr"
Python init
[W 11:51:32.411 CutterNotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/tmp/.mount_CutterwjvmJV/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 1573, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/tmp/.mount_CutterwjvmJV/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab'
[ WARNING : block size exceeding max block size at 0x0016a220
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0016ad1c
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0016d900
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x001766a4
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0017ee84
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0018c1c8
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0019eab0
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x001a2cf4
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x001b4b34
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0023c350
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00260278
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x002678b8
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0026e2ec
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00274c08
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00276adc
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0027d4bc
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00283e84
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0028a884
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00291280
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00297c7c
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x0029e6b0
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x002a50bc
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x002c0db8
[+] Try changing it with e anal.bb.maxsize
 WARNING : block size exceeding max block size at 0x00326874
[+] Try changing it with e anal.bb.maxsize
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze value pointers (aav)
[x] Value from 0x00000000 to 0x004e0a64 (aav)
[x] 0x00000000-0x004e0a64 in 0x0-0x4e0a64 (aav)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Type matching analysis for all functions (afta)
[x] Use -AA or aaaa to perform additional experimental analysis.

Task 1 finished

Task 2 finished
WARNING: r_list_length: assertion 'list' failed (line 55)
WARNING: r_list_length: assertion 'list' failed (line 55)
Failed to parse JSON for command "iVj": illegal value
Unknown format

No virtual tables found

[1]+  Errore di segmentazione (core dump creato) ~/Scaricati/Cutter-v1.7.2-x86_64.Linux.AppImage

```

### Steps to reproduce the behavior 
- unzip the apk
- start Cutter
- select the classes.dex file
- click on open
- in the next window ( Load Options) click ok
- wait for cutter to load 
- crash
[c.zip](https://github.com/radareorg/cutter/files/2468359/c.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by ITAYC0HEN** [comment]
Thanks for letting us know :)
I was able to reproduced on the Appimage release version, but wasn't able to reproduce the bug on Master.

Can you please check it on Cutter from git?

**Comment by ITAYC0HEN** [comment]
tried again on Appimage version and didn't have a crash - after a while (too much time), cutter loads fine.
I don't get the segfault message

**Comment by ITAYC0HEN** [comment]
can you reproduce this in radare2 as well?

**Comment by ytrewqytrewqytrewqytrewq1** [comment]
radare works fine

**Comment by xarkes** [comment]
I cannot reproduce here with master.

**Comment by ITAYC0HEN** [comment]
unline past, can't reproduce any related issue - Master branch.
@ytrewqytrewqytrewqytrewq1 can you please check again? I think this issue is resolved now.

**Comment by ytrewqytrewqytrewqytrewq1** [comment]
Master branch just compiled:
https://pastebin.com/ufx5vJJc
file:
[classes.zip](https://github.com/radareorg/cutter/files/2505271/classes.zip)
Steps:
start Cutter
select classes.dex
click on open
click on ok
wait the end of the analysis 
![screenshot from 2018-10-23 10-59-20](https://user-images.githubusercontent.com/32385661/47349131-36b32400-d6b3-11e8-9006-837cfa6c119b.png)


in the disassembly window scroll down until the end
crash

video:
[Screencast 2018-10-23 11_00_00.mp4.zip](https://github.com/radareorg/cutter/files/2505358/Screencast.2018-10-23.11_00_00.mp4.zip)

**Comment by ITAYC0HEN** [comment]
reproduced in Cutter, master. Wasn't able to reproduce on radare2 so it might indeed be a problem on our side

**Comment by a1ext** [comment]
looks like heap corruption, error on windows:
```Exception thrown at 0x0000000076F8A365 (ntdll.dll) in cutter.exe: 0xC0000005: Access violation reading location 0x000003846EA93A48.
```

**Comment by a1ext** [comment]
will fix it, assign please to me

**Comment by ITAYC0HEN** [comment]
This issue is now solved thanks to @a1ext's wonderful work. The issue origined in radare2.
Thank you for reporting and your collaboration :)
